- name: "Verify that required string variables are defined"
  assert:
    that: 
      - required_variable is defined
      - required_variable | length > 0
      - required_variable != None
    fail_msg: "{{ required_variable }} needs to be set for the role to work"
    success_msg: "Required variable {{ required_variable}} is defined"
  loop_control:
    loop_var: required_variable
  with_items:
    - "{{ TRAEFIK_HOSTNAME }}"
  no_log: True
  

## Traefik

- name: Setup Traefik namespace
  shell: echo "{{ lookup('template', 'namespace.yaml') }}" | kubectl apply -f -

- name: Helm Repo Add Traefik
  shell: helm repo add traefik https://helm.traefik.io/traefik
  register: result

- name: Helm Repo Update Traefik
  shell: helm repo update
  register: result

- name: Helm Install Traefik
  shell: helm install traefik traefik/traefik --namespace traefik
  register: result

- name: Helm Upgrade Traefik
  shell: helm upgrade traefik traefik/traefik --namespace traefik -f ../templates/values.yaml
  register: result